HMS UI/Controllers/ReceptionController.cs
using HMS_Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace HMS_UI.Controllers
{
    public class ReceptionController : Controller
    {
        private IConfiguration _configuration;
        public ReceptionController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Reception> receptionresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Reception/GetAppointments";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        receptionresult = JsonConvert.DeserializeObject<IEnumerable<Reception>>(result);
                    }
                }
            }
            return View(receptionresult);
        }
        public IActionResult AddAppointment()
        {
            return View();
        }
        [HttpPost("AddAppointment")]
        public async Task<IActionResult> AddAppointment(Reception reception)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(reception), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Reception/AddAppointments";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Patient appointment registered successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
   
    }
}

HMS UI/Views/Reception/AddAppointment.cshtml
@model HMS_Entity.Models.Reception

@{
    ViewData["Title"] = "AddAppointment";
}
<form method="post" enctype="multipart/form-data">
    <h1>Appointment Registration</h1>
</form>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddAppointment">
            <div class="form-group">
                <label asp-for="AppointmentId " class="control-label"></label>
                <input asp-for="AppointmentId" class="form-control" />
                <span asp-validation-for="AppointmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppointmentTime" class="control-label"></label>
                <input asp-for="AppointmentTime" class="form-control" />

            </div>
            <div class="form-group">
                <label asp-for="PatientId" class="control-label"></label>
                <input asp-for="PatientId" class="form-control" />
                <span asp-validation-for="PatientId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <input asp-for="DoctorId" class="form-control" />
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <input asp-for="EmployeeId" class="form-control" />
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            @if (ViewBag.status == "Ok")
            {
                <div class="alert alert-success">
                    @ViewBag.message
                </div>
            }
            else if (ViewBag.status == "Error")
            {
                <div class="alert alert-danger">
                    @ViewBag.message
                </div>
            }
        </form>
    </div>
</div>
<div>
    <a asp-action="ReceptionIndex">Back to List</a>
</div>

HMS UI/Views/Reception/ReceptionIndex.cshtml
@model IEnumerable<HMS_Entity.Models.Reception>
@{
    Layout = "~/shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-12">
        <h3>Reception</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>Appointment Id</th>
                    <th>Appointment Time</th>
                    <th> Patient Id</th>
                    <th> Doctor Id</th>
                    <th>Employee Id </th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>


                @foreach (var reception in Model)
                {

                    <tr>
                        <td>@reception.AppointmentId</td>
                        <td>@reception.AppointmentTime</td>
                        <td>@reception.PatientId</td>
                        <td>@reception.DoctorId</td>
                        <td>@reception.EmployeeId</td>
                        
                        



                        <td><a asp-controller="Reception" asp-action="UpdateAppointment" asp-route-AppointmentId="@reception.AppointmentId">Update</a></td>
                        <td><a asp-controller="Reception" asp-action="DeleteAppointment" asp-route-AppointmentId="@reception.AppointmentId">Cancel</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>